Task rung new
ThanhtaDEV/sample-code-FreeRTOS pull request #7
Opened 2024-11-08 15:00 UTC by vixhha

2024-11-08 15:17 UTC, ThanhtaDEV commented on Project_FreeRTOS/main/task_rung.h
>        sw_send.payload = BUZZER_SW_DISABLE;
Please swap values of 2 lines 18 and 19
follow me:
sw_send.id_Tx = IN_SW_1801P;
sw_send.id_Rx = OUT_BUZZER;

2024-11-08 15:19 UTC, ThanhtaDEV commented on Project_FreeRTOS/main/task_rung.h
>        xQueueSend(Platform_Queue, &sw_send, portMAX_DELAY);
remove this line 27

2024-11-08 15:24 UTC, ThanhtaDEV commented on Project_FreeRTOS/main/task_rung.h
>        sw_send.id_Rx = IN_SW_1801P;
Please swap values of 2 lines 18 and 19
follow me:
sw_send.id_Tx = IN_SW_1801P;
sw_send.id_Rx = OUT_BUZZER;

2024-11-08 15:27 UTC, ThanhtaDEV commented on Project_FreeRTOS/main/task_rung.h
>        xQueueSend(Platform_Queue, &sw_send, portMAX_DELAY);
please remove this line 21 "xQueueSend(Platform_Queue, &sw_send, portMAX_DELAY);"

2024-11-08 20:15 UTC, thaimq requested changes
Please check my review comments and update new commit ASAP!

2024-11-08 20:15 UTC, thaimq commented on Project_FreeRTOS/main/ha.c
Why do we have this file here?

2024-11-08 20:15 UTC, thaimq commented on Project_FreeRTOS/main/task_rung.h
>        if(xQueueSend(Rung_Queue, &sw_send, portMAX_DELAY) == pdPASS)
Please remove this line, we have another sending already.

2024-11-09 03:16 UTC, thaimq approved these changes
Checked

2024-11-09 03:16 UTC, merged